# Generated by Django 3.1.5 on 2021-01-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_auto_20210131_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='closetpost',
            name='date_frame',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
