# Generated by Django 3.1.5 on 2021-01-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_closetpost_date_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='closetimages',
            name='thumnail',
            field=models.BooleanField(default=False),
        ),
    ]
