# Generated by Django 3.1.5 on 2021-01-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_name', models.CharField(max_length=60)),
                ('line_id', models.CharField(max_length=60)),
                ('verify', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
            ],
        ),
    ]
